# Generated by Django 5.0.3 on 2024-10-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
