# Generated by Django 5.1.2 on 2024-10-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0002_trip_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="country",
            field=models.CharField(max_length=50),
        ),
    ]
